---

- hosts: all
  connection: local
  gather_facts: no
  tasks:
    - block:
        - name: determine hosts that are up
          ansible.builtin.ping:
            data: crash
#1          ansible.netcommon.net_ping:
#1            count: 2
#2          wait_for_connection:
#2            timeout: 5
#2          vars:
#2            ansible_connection: ssh
        - name: add devices with connectivity to the "running_hosts" group
          group_by:
            key: "running_hosts"
      rescue:
        - debug: msg="cannot connect to {{inventory_hostname}}"

- hosts: running_hosts
  gather_facts: no
  tasks:
  - name: upgrade all packages
    yum: name=* state=latest
    become: yes
  - name: send info to zabbix
    ansible.builtin.shell: /etc/zabbix/scripts/yum_updates.sh
    become: yes
