---
- hosts: all
  tasks:
  - name: upgrade all packages
    yum: name=* state=latest
    become: yes
  - name: send info to zabbix
    ansible.builtin.shell: /etc/zabbix/scripts/yum_updates.sh
    become: yes
