---

- hosts: all
  connection: local
  gather_facts: no
  tasks:
    - block:
        - name: determine hosts that are up
          wait_for_connection:
            timeout: 5
          vars:
            ansible_connection: ssh
        - name: add devices with connectivity to the "running_hosts" group
          group_by:
            key: "running_hosts"
      rescue:
        - debug: msg="cannot connect to {{inventory_hostname}}"

- hosts: running_hosts
  gather_facts: no
  tasks:
  - name: upgrade all packages
    yum: name=* state=latest
    become: yes
  - name: send info to zabbix
    ansible.builtin.shell: /etc/zabbix/scripts/yum_updates.sh
    become: yes

- hosts: localhost
  tasks:
  - name: "send mail"
    community.general.mail:
      host: mail.pavkamlc.cz
      port: 25
      to: 'pavel.mlcoch@pavkamlc.cz'
      sender: 'mgmt1@pavkamlc.cz'
      subject: 'Ansible-report dnf_updates.yml'
      body: 'System {{ ansible_hostname }} has been successfully provisioned.\nansible_inventory_sources\nansible_play_hosts_all\nansible_user'
    delegate_to: localhost
