---
- hosts: all
  connection: local
  gather_facts: no
  tasks:
    - block:
        - name: determine hosts that are up
          wait_for_connection:
            timeout: 5
          vars:
            ansible_connection: ssh
        - name: add devices with connectivity to the "running_hosts" group
          group_by:
            key: "running_hosts"
      rescue:
        - debug: msg="cannot connect to {{inventory_hostname}}"
        
- hosts: running_hosts
  gather_facts: no
  tasks:
#2  - name: Run the equivalent of pacman Syu as a separate step
#2    community.general.pacman:
#2      update_cache: yes
#2      upgrade: yes
#1    became: yes
#1  - name: send info to zabbix
#1    ansible.builtin.shell: /etc/zabbix/scripts/yum_updates.sh
#1    become: yes
  - name: pacman update
    ansible.builtin.shell: pacman -Syu
    become: yes
