---

- hosts: all
  connection: local
  gather_facts: no
  tasks:
  - name: Add the user 'james' with a bash shell, appending the group 'admins' and 'developers' to the user's groups
    user:
#      name: {{ myuser }}
      password: {{ mypassword }}
      name: asdf
      shell: /bin/bash
      groups: users
      append: yes
