---
- hosts: all
  connection: local
  vars:
    username: "{{ userplus }}"
    groups: "ansible,wheel"
    password: "{{ userpassword }}"
    remove_user: "{{ userminus }}"

  handlers:
  - name: "Restart sshd"
    service:
      name: "sshd"
      state: "restarted"
  tasks:
  - name: "Create user accounts"
    user:
      name:
      - "{{ username }}"
      groups:
      - "{{ groups }}"
      password:
      - "{{ password }}"
      state: "present"
  - name: "Remove old user accounts in remove_users"
    user:
      name: "{{ remove_user }}"
      state: "absent"
  - name: "Add authorized keys"
    authorized_key:
      user: "{{ username }}"
      key: "{{ lookup('file', '/home/ansible/.ssh/id_rsa.pub') }}"
      path: ~/.ssh/authorized_keys
  - name: "Allow admin users to sudo without a password"
    lineinfile:
      dest: "/etc/sudoers" # path: in version 2.3
      state: "present"
      regexp: "^%wheel"
      line: "%wheel ALL=(ALL) NOPASSWD: ALL"
  - name: "Disable root login via SSH"
    lineinfile:
      dest: "/etc/ssh/sshd_config"
      regexp: "^PermitRootLogin"
      line: "PermitRootLogin no"
    notify: "Restart sshd"
...
