---
- hosts: all
  connection: local
  vars:
    users:
    - username:
      - "{{ userplus }}"
      groups: "ansible,wheel"
    remove_users: "{{ userminus }}"

handlers:
  - name: "Restart sshd"
    service:
      name: "sshd"
      state: "restarted"
  tasks:
  - name: "Create user accounts"
    user:
      name:
      - "{{ item.username }}"
      groups:
      - "{{ item.groups }}"
      state: "present"
    with_items:
      - "{{ users }}"
  - name: "Remove old user accounts in remove_users"
    user:
      name: "{{ item }}"
      state: "absent"
    with_items: "{{ remove_users }}"
  - name: "Add authorized keys"
    authorized_key:
      user:
      - "{{ item.username }}"
      key: "{{ lookup('file', '/home/ansible/.ssh/id_rsa.pub') }}"
      path: ~/.ssh/authorized_keys
    with_items:
      - "{{ users }}"
  - name: "Allow admin users to sudo without a password"
    lineinfile:
      dest: "/etc/sudoers" # path: in version 2.3
      state: "present"
      regexp: "^%wheel"
      line: "%wheel ALL=(ALL) NOPASSWD: ALL"
  - name: "Disable root login via SSH"
    lineinfile:
      dest: "/etc/ssh/sshd_config"
      regexp: "^PermitRootLogin"
      line: "PermitRootLogin no"
    notify: "Restart sshd"
...
