- name: Add the user 'james' with a bash shell, appending the group 'admins' and 'developers' to the user's groups
  ansible.builtin.user:
    name: ansible
    password: {pass}
    shell: /bin/bash
    groups: admins,developers
    append: yes
